### ISSUE TITLE
Disabled routes aren't disabled

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-operator#111]
When specifying disabledRoutes to `['camel', 'Camel', 'Quartz']` the respective routes are still accessible in UI and served by Hawtio.

**Comment by tadayosi** [comment]
@mmuzikar That's weird, but the config doesn't look a bit right. They should match the exact root path name for each plugin, so it should look something like `['camel', 'quartz']` (no capital letters).

**Comment by mmuzikar** [comment]
That's why I have both capital and lowercase `camel`. Neither of them disable the route.

**Comment by phantomjinx** [comment]
The syntax is the **path** of the route not the identifier. So it is `/camel` and `/quartz`

![Screenshot_20240305_125720](https://github.com/hawtio/hawtio-operator/assets/1634180/8f64c50a-6486-46ea-bbbb-69ed1495ba2c)
