### ISSUE TITLE
Support changing the image url in Hawtio CRD

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-operator#38]
There is `version` field that allows us to change it from `latest` in the `Hawtio` CRD, but for dev purposes sometimes it's also convenient to change the docker image url from `docker.io/hawtio/online` to somewhere else.

**Comment by astefanutti** [comment]
The image repository can be overwritten either with the `ImageRepository` build variable, or the `IMAGE_REPOSITORY` environment variable: 

https://github.com/hawtio/hawtio-operator/blob/5956d02c1975a5b41524310ef5c4b0e18b77deef/pkg/resources/container.go#L57-L72

**Comment by tadayosi** [comment]
Ah ok, thanks. Closing.
