### ISSUE TITLE
Document migration steps from hawtio-operator 0.3.0 to 0.4.0

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-operator#49]
There are some breaking changes since hawtio-operator 0.3.0  (#46, #48). We need to document for <=0.3.0 users the migration steps of their hawtio applications to 0.4.0. Notable changes include:
* CRD apiVersion upgraded from `apiextensions.k8s.io/v1beta` to `apiextensions.k8s.io/v1`
* `spec.rbac.enabled` field is removed from CR and types API. RBAC support is now always on and cannot be turned off.

----

@astefanutti I think what we really need to document is for users with the following Hawtio CR yaml (either with `true` or `false`) to just remove the field from the spec. Is my understanding correct?
```yaml
spec:
    rbac:
        enabled: {true|false}
```

**Comment by astefanutti** [comment]
Yes, your understanding is correct. AFAIK, the CRD version upgrade should be handled by OLM smoothly.

**Comment by tadayosi** [comment]
Fixed dbdf94e77358bcfa959560136f5980c65da79ae3

**Comment by astefanutti** [comment]
Thanks @tadayosi 👍🏼.
