### ISSUE TITLE
Upgrade hawt.io CRD to v1beta1 or v1

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-operator#67]
We already enjoyed `hawt.io/v1alpha1` for long time, and I think the CRD is already stabilised to some extent. It's good time to move to v1beta1 or v1 depending on how much we expect to add new features or change the API.

https://github.com/hawtio/hawtio-operator/blob/0.5.0/deploy/crd/hawtio_v1alpha1_hawtio_crd.yaml

**Comment by tadayosi** [comment]
cc @phantomjinx @mmelko

**Comment by tadayosi** [comment]
@phantomjinx If you are fine, I can take care of it.

**Comment by phantomjinx** [comment]
Oh! Sorry @tadayosi missed your comment. Have done a commit on the 2.x branch with the removal of the `ImageVersion` and testing once it builds. If you have already done it then I can fix the merge when I get to merging 2.x onto main.

**Comment by tadayosi** [comment]
@phantomjinx Fine. Please send a pull req once you're done.

Can you please pay more attention to upstream communication next time?  Since it's our primary communication channel.
