### ISSUE TITLE
Consider dropping version in CR and baking it into the operator

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-operator#71]
### Overview

There are a couple of recommended best practices for how operators handle the version of the operand as detailed [here](https://sdk.operatorframework.io/docs/best-practices/best-practices/), namely:
1. Operator fan-out - where the Operator allows the user to specify the version in the custom resource
2. single version - where the Operator is tied to the version of the operand.
3. hybrid approach - where the Operator is tied to a range of versions, and the user can select some level of the version

Currently, hawtio uses the first approach, specifying a default version in the CR yet allowing the user to change this, as appropriate. In my personal view, I think the upgrade to Hawtio-Online 2 would be a good time to switch the operator to the 2nd approach.

The 2nd approach is, to my mind, simpler in that it maintains a 1:1 relationship between operator and operand. It ensures that the upgrade process is controlled by the OLM's operator versioning pattern. As the operator is responsible for installing a number of resources, including the deployment, the current design allows the possibility that the user could install a much later operand in an old operator, resulting in a situation where all the resources in the operator no longer correctly handle features of the new operand.

The current approach only seems to specify the version number as a default. Therefore, it is possible for the user to change this to *any* version / tag, without any perceived limits (I cannot find any checks on the version in the operator so it may just be my ignorance :-) ).

### Suggestion for Change

Remove the version from the CR and instead handle it with an environment variable and golang constant in the same manner as the image repository. This would allow the operator to be compiled with a 1:1 relationship to the operand (the golang constant) but would maintain a degree of customization by having the environment variable be available to override if necessary, eg. development / testing.

The removal of the version from the CR would be useful to remove prior to the upgrading of the CRD to 1.0.0. After that, *if* we chose to make this change, it would be more problematic to include such a change in a micro-version update.

**Comment by tadayosi** [comment]
That makes sense. Let's do it.

**Comment by phantomjinx** [comment]
Fix was already present on 1.x branch ~but now in PR for review onto main.~ and now merged with https://github.com/hawtio/hawtio-operator/pull/87.
