### ISSUE TITLE
Upgrade the go version to align with internal build systems

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-operator#81]
Receiving odd golang errors with the building of the operator in build systems. Identified that the `go.mod` file was generated with golang 1.13 while using later version (1.19) for the golang image building the operator. Internal build systems, in turn, use golang 1.20.

So to mitigate and hopefully remove any errors, the `go.mod` file will be re-generated using golang 1.20, aligning with the build systems.

**Comment by tadayosi** [comment]
Is it still an issue after #79?  I requested you review a few days ago.

**Comment by phantomjinx** [comment]
Rebased `1.x` branch on `main` to bring in updates.
